install.packages(pkgs = c("devtools", 
                          "packrat", 
                          "plyr", 
                          "dplyr", 
                          "tidyr", 
                          "lubridate", 
                          "ggplot2", 
                          "ggvis", 
                          "scales", 
                          "knitr", 
                          "rmarkdown", 
                          "servr",
                          "xtable", 
                          "shiny", 
                          "shinydashboard", 
                          "RSQLite", 
                          "rmongodb", 
                          "RColorBrewer", 
                          "Rcpp", 
                          "RCurl", 
                          "XLConnect", 
                          "rJava", 
                          "sendmailR", 
                          "htmlwidgets", 
                          "DT", 
                          "dygraphs", 
                          "leaflet", 
                          "XML",
                          "maps", 
                          "maptools",
                          "mapdata", 
                          "mapproj"), 
                 lib = "/usr/lib/R/site-library", 
                 repos = "http://cran.case.edu")
